dnaseq = input("enter DNA sequence:")
print(dnaseq)
seq1=dnaseq.replace('A','-')
seq2=seq1.replace('T','A')
seq3=seq2.replace('-','T')
seq4=seq3.replace('G','+')
seq5=seq4.replace('C','G')
seq6=seq5.replace('+','C')
print(seq6)
